<ExpandablePanel>:
    orientation: 'vertical'
    spacing: 0
    padding: 0
    size_hint_y: None
    height: self.header_height if not self.is_expanded else self.header_height + self.panel_spacing + self.ids.content.height
    
    canvas.before:
        Color:
            rgba: self.bg_color
        Rectangle:
            pos: self.pos
            size: self.size
    
    BoxLayout:
        id: header
        orientation: 'horizontal'
        size_hint_y: None
        height: root.header_height
        padding: [dp(15), 0, dp(15), 0]
        
        canvas.before:
            Color:
                rgba: ThemeColors.current["TAB_BACKGROUND"]
            Rectangle:
                pos: self.pos
                size: self.size
        
        Label:
            text: root.title
            color: root.text_color
            halign: 'left'
            valign: 'middle'
            text_size: self.size
            size_hint_x: 0.9
        
        Widget:
            size_hint_x: 0.1
            
            canvas.after:
                Color:
                    rgba: root.text_color
                Triangle:
                    points: root.get_arrow_points(self.center_x, self.center_y)
    
    BoxLayout:
        id: content
        orientation: 'vertical'
        size_hint_y: None
        height: 0 if not root.is_expanded else self.minimum_height
        opacity: 0 if not root.is_expanded else 1
        disabled: not root.is_expanded