#:import dp kivy.metrics.dp
#:import colors ui.styles.colors

<HintTextInput>:
    size_hint_y: None
    height: dp(45)
    multiline: False
    write_tab: False
    padding: [dp(14), dp(14)]
    font_size: dp(14)

    background_normal: ''
    background_active: ''
    background_disabled_normal: ''

    hint_text_color: (colors.ThemeColors.current["TEXT_COLOR"][0]*0.5, colors.ThemeColors.current["TEXT_COLOR"][1]*0.5, colors.ThemeColors.current["TEXT_COLOR"][2]*0.5, 0.85)
